### ISSUE TITLE
HasTrigger is not working with synonymous tables

### ISSUE THREAD

**Issue by iahmed9312** [sjh37/EntityFramework-Reverse-POCO-Code-First-Generator#813]
After updating to EFCore7 (HasTrigger) is now required before inserting to a table, and thankfully POCO is updated since v3.8.0 . However,  I have added table (that has trigger) as synonymous from another database but (HasTrigger ) is not added by POCO.

**Comment by sjh37** [comment]
Hi. `HasTrigger` was added to v3.8.1 and enhanced in v3.8.2.
See [release v3.8.2 notes](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/releases/tag/v3.8.2)

Please show me the SQL to create the trigger for the table, and the SQL for the table so that I may test it.

**Comment by sjh37** [comment]
I also wanted to check you have set `Settings.TemplateType = TemplateType.EfCore7` in your .tt settings file.

**Comment by iahmed9312** [comment]
Thank you for your reply.

The template is set to Settings.TemplateType = TemplateType.EfCore7

To replicate my situation please follow the steps:
1. Create new database (Database1)
2. Create table (Table1)
3. Create trigger for Table1 

If you run POCO in Database1 it will run correctly and it will add (HasTrigger to Table1)

**To get to my issue please follow the steps:**
1. Create a new database (Database2)
2. Create new Synonym pointing to Database1.dbo.Table1

Now if you run POCO on Database2 it will run correctly except it will not add (HasTrigger to Table1)

I hope it is clear.

**Comment by iahmed9312** [comment]
Please note you have to change _FilterSettings.IncludeSynonyms = true_ in your  .tt settings file

**Comment by sjh37** [comment]
Try the attached file. It only works on SQL Server currently. Let me know if it works for you.
[EF.Reverse.POCO.v3.zip](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/files/12553412/EF.Reverse.POCO.v3.zip)

**Comment by iahmed9312** [comment]
Thank you very much, it is working perfectly!

**Comment by sjh37** [comment]
Released in v3.9.0
